### PR TITLE
simplify forkjoin code

### LINKED ISSUE #1729: Build Bug: org.apache.pekko.dispatch.PekkoJdk9ForkJoinPool is not on the classpath
Even the PekkoJdk9ForkJoinPool is on the final result jar, but it does not on the classpath.

How to reproduce:
1. using Java 21
2. sbt console
3.
```scala
Welcome to Scala 2.13.16 (Java HotSpot(TM) 64-Bit Server VM, Java 21.0.5).

scala> classOf[org.apache.pekko.dispatch.PekkoJdk9ForkJoinPool]
                                         ^
       error: type PekkoJdk9ForkJoinPool is not a member of package org.apache.pekko.dispatch

scala> 
```

I think that's maybe caused by of the `Jdk9.scala`

### PR DESCRIPTION
**Pull request by pjfanning**
with Java 8 support gone in Pekko 2.x, I can remove the reflection based code for fork join dispatchers

fixes #1729

### CODE REVIEW

File: actor/src/main/scala/org/apache/pekko/dispatch/ForkJoinExecutorConfigurator.scala [hunk 1]
```diff
@@ -30,15 +28,12 @@ object ForkJoinExecutorConfigurator {
...
       asyncMode: Boolean)
-      extends ForkJoinPool(parallelism, threadFactory, unhandledExceptionHandler, asyncMode)
+      extends ForkJoinPool(parallelism, threadFactory, unhandledExceptionHandler, asyncMode,
+        0, maximumPoolSize, 1, null, ForkJoinPoolConstants.DefaultKeepAliveMillis, TimeUnit.MILLISECONDS)
       with LoadMetrics {
-    def this(
-        parallelism: Int,
-        threadFactory: ForkJoinPool.ForkJoinWorkerThreadFactory,
-        unhandledExceptionHandler: Thread.UncaughtExceptionHandler) =
-      this(parallelism, threadFactory, unhandledExceptionHandler, asyncMode = true)
```
Comment (raboof) [inline actor/src/main/scala/org/apache/pekko/dispatch/ForkJoinExecutorConfigurator.scala:41]: I suppose this was here for binary compatibility, but indeed we don't need to preserve that

Comment (pjfanning) [reply actor/src/main/scala/org/apache/pekko/dispatch/ForkJoinExecutorConfigurator.scala:41]: it's an internal class so I think it is safe to remove the unused constructors in a major release
